### ISSUE TITLE
Documentation on REST Interface

### ISSUE THREAD

**Issue by KlausSchaefers** [penpot/penpot-docs#109]
Hi,

I am trying to support Penpot in the Luisa framework (https://luisa.cloud). I was trying to reverse engineer the REST API, but for me the data structure is not clear. It´s quite different from the JSON Figma or Sketch produce... 

I often see that there or some arrays like 

```
["^ ", "~:y", 113, "~:hide-fill-on-export", false, "^O", 0, "^P",…]
```

I assume this is a list of key value pairs. But I would like to confirm this. Are there somewhere schema defined?

Cheers,

Klaus

**Comment by hirunatan** [comment]
I'm afraid the Penpot backend API is not REST. It's a kind of RPC calls, that frontend clojure code may invoke with the same arguments and data types as a normal function call.

We have just published a [figma exporter plugin](https://community.penpot.app/t/export-figma-to-penpot/1684/5), that uses a Penpot library you can use from javascript. And we are documenting some parts of the data model, that hope we can publish in a few days. This is not exactly for your use case, but it may give you some clues.

If you want to export data from Penpot to Luisa, perhaps you can analyze the .zip format we generate when you download a file, with annotated svg files.
