### ISSUE TITLE
Minor: Wrong link in mailcatcher section on "Development environment"

### ISSUE THREAD

**Issue by jdittrich** [penpot/penpot-docs#113]
In 

> Instead, it stores them in memory and allows to browse them via a web interface similar to a webmail client. Simply navigate to:
> [http://localhost:1080](https://help.penpot.app/technical-guide/developer/devenv/#email)

The link named actually leads to https://help.penpot.app/technical-guide/developer/devenv/ instead of http://localhost:1080

**Comment by hirunatan** [comment]
You are true! This is fixed now. Thank you for pointing it out.
