### ISSUE TITLE
Finding docker installation instructions is tedious

### ISSUE THREAD

**Issue by jorisroovers** [penpot/penpot-docs#127]
Hi, I’m a new penpot user. Penpot looks great, thanks for creating it.

I wanted to try running Penpot by using docker. 

To get to the [Start Penpot section](https://help.penpot.app/technical-guide/getting-started/#start-penpot) with the 2 command line instructions I needed, I had to navigate 4 pages (and 5 clicks) from the home page. At least one of the links I had to click along the way was far down a page in a forum post.

For a UX product, I think that’s not the best UX ?  (pun intended :-))

I think an ideal solution would be a section expanding/appearing when clicking the “self-host install”  button right on the homepage that shows the 2 lines to install using docker with a link to more info for those that need it. Perhaps with a different tab for Elestio within that appearing section.

I also think a one-liner pointing to instructions on how to install docker suffices, I had to scroll through all the docker installation instructions I didn’t need a few times along the way. I understand the Penpot audience isn’t developers, but I still think it was too much.

Hope this is useful feedback! Screenshots and details below

[https://penpot.app/](https://penpot.app/)

![image](https://user-images.githubusercontent.com/575086/216587364-05acd72f-6ad6-4469-8d4e-249e659972f4.png)

[https://penpot.app/self-host](https://penpot.app/self-host)

![image](https://user-images.githubusercontent.com/575086/216587756-c0b8679a-b32a-471e-bbf5-8f7c53e060e8.png)

[https://penpot.app/self-host#installing-options](https://penpot.app/self-host#installing-options)

![image](https://user-images.githubusercontent.com/575086/216587846-54696f19-8c95-410c-af01-c517610a0436.png)

[https://community.penpot.app/t/self-hosting-penpot-ii/2337](https://community.penpot.app/t/self-hosting-penpot-ii/2337)

![image](https://user-images.githubusercontent.com/575086/216587953-8c28d568-d421-4ec3-9b07-8adfaa256b67.png)

[https://help.penpot.app/technical-guide/getting-started/#install-with-docker](https://help.penpot.app/technical-guide/getting-started/#install-with-docker)

![image](https://user-images.githubusercontent.com/575086/216588008-77c049e1-6f3b-481b-bcf3-251105ecdcd5.png)

**Comment by hirunatan** [comment]
You are true. There was the intention of having a shortcut path for people that already knows what's this all about. But somehow it got lost.

I have changed the two buttons at the top of the landing page, to directly send you to the relevant info if you know what do you want. Other people can just keep scrolling.
