### ISSUE TITLE
create user with script

### ISSUE THREAD

**Issue by rvmadeit** [penpot/penpot-docs#222]
Hi, in the documentation there is a command: `sudo docker exec -ti webapp_penpot-backend_1 bash .manage.sh create-profile`
but the manage.sh is no longer in the docker but when i try with the command: `sudo docker exec -ti webapp_penpot-backend_1 python3 ./manage.py create-profile`

![image](https://github.com/penpot/penpot-docs/assets/74316943/b5520cf5-7176-402d-869e-bbe5b4f13c13)
the script launch and I can create a user, but I can't log in with the web interface, I have an error wrong email or password

**Comment by papgaabor** [comment]
@rvmadeit  The password has to be at least 8 characters long, otherwise you will get the "Email or Password is incorrect" message. Unfortunately the create-profile script doesn't check for password length.

+1 for updating the docker command to `manage.py`, it took me some time to figure it out.
