### ISSUE TITLE
Misleading statement on adaptability

### ISSUE THREAD

**Issue by 12people** [penpot/penpot-docs#23]
The line "Extreme adaptability: contributions can range from add-ons and plugins to core functionality." is misleading. It implies that Penpot supports add-ons and plugins, but it doesn't.

**Comment by myfunnyandy** [comment]
This is more like an aspirational statement (it will no longer be an aspiration during next year). However, we urdestand that it can be misleading and we're already working in whole new messages for the public sites so this will definitelly change soon.
