### ISSUE TITLE
404 Not Found when clicking on Developer guide in the footer

### ISSUE THREAD

**Issue by mlgarchery** [penpot/penpot-docs#26]
The URL it tries to access is: https://help.penpot.app/developer-guide
![Screenshot from 2021-07-16 11-46-58](https://user-images.githubusercontent.com/16239564/125928450-68079d9a-efb5-4d81-a1a1-411bf42a4e67.png)

**Comment by RollingSnack** [comment]
Oh, hi. I fix this one, but it seems that I forget to close it in my pull requests.
Can anyone help close it?

**Comment by hirunatan** [comment]
@RollingSnack your PR is closed now, isn't it?
