### ISSUE TITLE
Update information to docs

### ISSUE THREAD

**Issue by jimboolio** [penpot/penpot-docs#44]
Hello!

Just a small improvement idea. "How to update" section to the technical guide could be useful. Updating docker containers is probably quite easy, but since I am still learning it, I am afraid of breaking something.

**Comment by jimboolio** [comment]
Oh, I am idiot, the docker compose script seems to pull latest images if I understood correctly

**Comment by hirunatan** [comment]
Haha... don't blame yourself. It's true that this is not very obvious unless you are a docker expert.

If you do a docker-compose pull, it fetches the latest penpot image. And next time you do up, it destroys the containers and recreates them with the new version.

We'll add this to the help center as soon as possible. Thanks for noticing.
