### ISSUE TITLE
In devenv, how do I connect to penpot once I start it running?

### ISSUE THREAD

**Issue by PaulSchulz** [penpot/penpot-docs#46]
The documentations describes how to get the devenv working in tmux, but can I connect with a browser?

Connecting to http://localhost:3448/dashboard works, but nothing connects on http://localhost:8888
It doesn't appear to be working.

**Comment by niwinz** [comment]
why you need the 8888?

Devenv once running the main host & port is http://localhost:3449

**Comment by PaulSchulz** [comment]
Thanks.. That works.
 I can add this to the develop doc if you are happy to wait for a pull request.

**Comment by PaulSchulz** [comment]
https://github.com/penpot/penpot-docs/pull/47
