### ISSUE TITLE
Section on demo users is inaccurate/outdated

### ISSUE THREAD

**Issue by viviicat** [penpot/penpot-docs#55]
I had to use the option `disable-demo-users` to disable demo users, but https://help.penpot.app/technical-guide/configuration/#demo-users suggests that the demo users setting is opt-in. It appears to be opt-out as of 1.10.

**Comment by johncadengo** [comment]
I used `disable-demo-users` and when I go to the homepage, it still has a link for "Create Demo Account"

When I press "Create Demo Account" it gives me "Unexpected Validation Error"

Is there a way to remove the link to even create a demo account

![Screen Shot 2022-03-09 at 1 38 59 PM](https://user-images.githubusercontent.com/561587/157540640-2e8efa2c-827b-469e-a646-8d5d0019422a.png)
?

**Comment by niwinz** [comment]
This will be fixed for the next release. Demo users was enabled by default from the start of project, so this is probably a doc issue yes. But from the next release they will be disabled by default.
