### ISSUE TITLE
Recommended system requirements

### ISSUE THREAD

**Issue by wesleyguirra** [penpot/penpot-docs#74]
What are the recommended system requirements?

CPU
Amount of RAM
Space

for the penpot run without problems

**Comment by niwinz** [comment]
It all depends on what you are going to do with penpot, the bigger files the more need for "memory". Our saas is using 8gb memory 2 core ARM64 virtual machines we can have ono or more depending on the load. But our internal instances uses one a VM with 4GB and 1 core.

The disk space, it all depends your use, so you cant estimate it.

**Comment by v3ss0n** [comment]
> It all depends on what you are going to do with penpot, the bigger files the more need for "memory". Our saas is using 8gb memory 2 core ARM64 virtual machines we can have ono or more depending on the load. But our internal instances uses one a VM with 4GB and 1 core.
> 
> The disk space, it all depends your use, so you cant estimate it.

How many users using in that instance? 
Mine have 64 GB ram and only me testing for a day , now its taing 24 GB already.

**Comment by niwinz** [comment]
> > It all depends on what you are going to do with penpot, the bigger files the more need for "memory". Our saas is using 8gb memory 2 core ARM64 virtual machines we can have ono or more depending on the load. But our internal instances uses one a VM with 4GB and 1 core.
> > The disk space, it all depends your use, so you cant estimate it.
> 
> How many users using in that instance? Mine have 64 GB ram and only me testing for a day , now its taing 24 GB already.

This is how JVM works, if you don't limit it, it will use a huge a mount of ram (running less frequently the garbage collector). It also depends if you run all the penpot processes in one VM or each one has a different VM. In case is all in one, for a small instance 4gb or 8gb should be enough (it not depends strictly on number of users, it depends on the size of the penpotfiles that users of the instance are working on).

My recommendation is: start with small instance, and if you start getting out of memory errors on backend logs, increase. There are no silver bullet specs that works in all cases.

**Comment by v3ss0n** [comment]
thanks a lot , i will limit ram usage on the container.
