### ISSUE TITLE
Optimize the "Libraries & templates" page

### ISSUE THREAD

**Issue by valioDOTch** [penpot/penpot-docs#75]
I stumbled accross the Libraries and template page [as I scanned the comments in a ticket and found this one](https://github.com/penpot/penpot/issues/967#issuecomment-1047579553)
https://penpot.app/libraries-templates.html
![image](https://user-images.githubusercontent.com/800467/161723611-bca66779-b49c-4d15-85fc-ba02c606e45b.png)

I haven't used to templates before and wanted to get to know them.
I report my impressions and possible improvements for said page from a UX engineer perspective herein, which I'd deem useful given this onboarding scenario.

I realized that I was supposed to download and to somehow import the libraries. I didn't know how to though in detail.

Reading the links I think it's nice to know that I can contribute, but this targets clearly the "most savvy users", not the novel ones, which want to just use the import.
**=>** I would consider to place the link "How to contribute" at the third position in that link list.

One of the links lead me to https://help.penpot.app/user-guide/import-export which with the exporting parts.
**=>** It would be more helpful, if it would either start the other way round 
**=>** alternatlively change the link to jump to https://help.penpot.app/user-guide/import-export/#importing-import
**=>** additionally consider to remove the "& export" text from the link. It's not relevant to users whether the linked article is also about exporting files or whether that one is separated.

Furthermore, I'd suggest to consider adding a GIF screencast to the wiki article (or probably the page as a popup?), which shows a walkthrough for the import process.

**Comment by myfunnyandy** [comment]
Hi @valioDOTch,

Totally agree, even though this section is still the bare minimum version of our further plans, we need to provide better explanations about how to use the templates now. We've created a User Story to improve this page where we linked this issue so we can take it into account at the time we go for it: https://tree.taiga.io/project/penpot/us/3222?milestone=262806

Thank you very much for taking the time to write down such a detailed proposal.

**Comment by valioDOTch** [comment]
Looks already much better :+1: :-)
